pipeline:
  name: Build 1383051_Devops_Casestudy_Web_app
  identifier: Build_1383051_Devops_Casestudy_Web_app_1692463301164
  projectIdentifier: CIWebApp
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1692456884886
                    repoName: 1383051_Devops_Casestudy_Web_app
                    build:
                      type: branch
                      spec:
                        branch: main
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1692456884886
        repoName: rahulkalithkar/1383051_Devops_Casestudy_Web_app
        build: <+input>
